---
version: "2.0"
services:
  service-1:
    image: yourusername/nestastrosl:tag
    expose:
      - port: 4321
        as: 80
        to:
          - global: true
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 4
        memory:
          size: 2GB
        storage:
          - size: 2GB
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
